security:
    session_fixation_strategy: migrate
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto
            cost: 16
            time_cost: 4
            memory_cost: 1024
        App\Entity\User:
            algorithm: auto
            cost: 16
            time_cost: 4
            memory_cost: 1024
    providers:
        users_in_memory: { memory: null }
        database:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt))/
            security: false
        public:
            pattern: ^/(build|bundles|media|translations)/
            security: false
        main:
            pattern: ^/
            lazy: true
            provider: database
            entry_point: App\Security\AppAuthenticator
            custom_authenticators:
                - App\Security\AppAuthenticator
            logout:
                path: user_logout
                target: home_index
                invalidate_session: true
            form_login:
                login_path: user_login
                check_path: user_login_check
                default_target_path: user_account
                use_forward: false
                use_referer: false
                enable_csrf: true
            # json_login:
            #     check_path: api_login
            http_basic:
                realm: Secured Area
            remember_me:
                secret: '%env(APP_SECRET)%'
                lifetime: 604800 # 1 week
            switch_user: true
    role_hierarchy:
        ROLE_ADMIN:         [ROLE_USER]
        ROLE_SUPER_ADMIN:   [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    access_control:
        - { path: "^/([a-z]{2}\/)?admin",                   requires_channel: https,    roles: [IS_AUTHENTICATED_FULLY, ROLE_ADMIN  ] }
        - { path: "^/([a-z]{2}\/)?account/login$",          requires_channel: https,    roles: [PUBLIC_ACCESS                       ] }
        - { path: "^/([a-z]{2}\/)?account/login/check$",    requires_channel: https,    roles: [PUBLIC_ACCESS                       ] }
        - { path: "^/([a-z]{2}\/)?account/recover$",        requires_channel: https,    roles: [PUBLIC_ACCESS                       ] }
        - { path: "^/([a-z]{2}\/)?account/reset-password$", requires_channel: https,    roles: [PUBLIC_ACCESS                       ] }
        - { path: "^/([a-z]{2}\/)?account",                 requires_channel: https,    roles: [IS_AUTHENTICATED_FULLY              ] }
        - { path: "^/([a-z]{2}\/)?",                        requires_channel: https,    roles: [PUBLIC_ACCESS                       ] }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
            App\Entity\User:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
